version: "3.9"

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app   # Mount current directory for live code changes (dev only)
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

